name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        path: src/

    - name: Encode with SourceGuardian
      uses: astoltz/sourceguardian-encode-action@master
      with:
        source: 'src'
        recursive: 0
        destination: 'dst'
        phpversion: |
          8.2
          8.3
          8.4
        entangle: 5
        prepend-code: '@src/sg_header.php'
        keep-file-date: true
        no-default-starter: true
        projid: ${{ secrets.MAIN_PROJECT_ID }}
        projkey: ${{ secrets.MAIN_PROJECT_KEY }}
        external: sg_api_test.lic
        catch: ERR_ALL=sg_catchall
        const: |
          build_id=developer1
          license_file="sg_api_test.lic"

    - name: Encode with SourceGuardian - sg_error_page.php
      uses: astoltz/sourceguardian-encode-action@master
      with:
        source: src/sg_error_page.php
        recursive: false
        destination: 'dst/src'
        phpversion: |
          8.2
          8.3
          8.4
        entangle: 5
        keep-file-date: true
        no-default-starter: true
        projid: ${{ secrets.ERROR_PAGE_PROJECT_ID }}
        projkey: ${{ secrets.ERROR_PAGE_PROJECT_KEY }}
        const: |
          build_id=developer1
          license_file="sg_api_test.lic"

    - name: Upload Artifact - base
      uses: actions/upload-artifact@v4
      with:
        name: base-application
        path: src/

    - name: Upload Artifact - sg-encoded
      uses: actions/upload-artifact@v4
      with:
        name: sg-encoded
        path: dst/src/
